export const ADD_FIELD = 'ADD_FIELD';
export const REMOVE_FIELD = 'REMOVE_FIELD';
export const SET_IS_REQUIRED = 'SET_IS_REQUIRED';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const CHANGE_QUESTION_TEXT = 'CHANGE_QUESTION_TEXT';

