export const ADD_FIELD = 'ADD_FIELD';
export const REMOVE_FIELD = 'REMOVE_FIELD';
export const SET_IS_REQUIRED = 'SET_IS_REQUIRED';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const CHANGE_QUESTION_TEXT = 'CHANGE_QUESTION_TEXT';
export const TOGGLE_EDDIT_CHOICE = 'TOGGLE_EDDIT_CHOICE';
export const CHANGE_CHOICE_TEXT = 'CHANGE_CHOICE_TEXT';
export const REMOVE_CHOICE = 'REMOVE_CHOICE';
export const ADD_CHOICE = 'ADD_CHOICE';

